#! /usr/bin/python3
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, Gdk
from pathlib import Path
import subprocess
sysget = subprocess.getoutput
appsdir = Path('/usr/share/applications')
flatpakappsdir = Path('/var/lib/flatpak/exports/share/applications')

def read_dekstop_files(dir):
    for app in list(dir.iterdir()):
        try:
            print('\n\nBegin of .desktop')
            NoDisplay = False
            file = open(app, 'r')
            lines = file.readlines()
            
            for line in lines:
                if line.startswith("NoDisplay=true"):
                    NoDisplay = True
                    print(line)
                else:
                    pass

            for line in lines:
                
                if NoDisplay == False:

                    if line.startswith("Name="):
                        print(line)
                    elif line.startswith("Exec="):
                        print(line)
                    elif line.startswith("Icon="):
                        print(line)
                    else:
                        pass
            print('End of .desktop\n\n')
                    
        except:
            pass

read_dekstop_files(appsdir)
read_dekstop_files(flatpakappsdir)