add_newline = false
format = """\
[](green)\
$username\
$directory\

$git_branch\
$git_status\
[](fg:#769ff0 bg:#74d7ec)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#74d7ec bg:#1e1e2e)\
"""

right_format = """
$battery\
$time\
[ ](fg:#45475a)\
"""

[username]
show_always = true
style_user = "fg:#1e1e2e bg:#a6e3a1"
style_root = "bg:#9A348E"
format = '[$user]($style)[](bg:blue fg:green)'
disabled = false
[directory]
style = "fg:black bg:blue"
format = "[ $path ]($style)[](fg:blue bg:#769ff0)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#769ff0"
format = '[[ $symbol $branch ](fg:#394260 bg:#769ff0)]($style)'

[git_status]
style = "bg:#769ff0"
format = '[[($all_status$ahead_behind )](fg:#394260 bg:#769ff0)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
format = '[(\($virtualenv\) )]($style)'
style = 'white'
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = ""
format = '[[ $time ](fg:#cdd6f4 bg:#45475a)]($style)'


[battery]
disabled = false
format='[](#303446)[$symbol$percentage]($style)[ ](fg:#303446 bg:#45475a)'
[[battery.display]]
threshold = 20
style = 'bold #e78284 bg:#303446'
[[battery.display]]
threshold = 40
style = 'bold #e78284 bg:#303446'
[[battery.display]]
threshold = 80
style = 'bold #ef9f76 bg:#303446'
[[battery.display]]
threshold = 100
style = 'bold #a6e3a1 bg:#303446'



