MediaLayerDefault = true
ShowButtonOutlines = true
EnablePixelShift = false
FontTemplate = "dejavu"
AdaptiveBrightness = true
ActiveBrightness = 128
PrimaryLayerKeys = [
    { Text = "F1",              Action = "F1"        },
    { Text = "F2",              Action = "F2"         },
    { Text = "F3",              Action = "F3"      },
    { Text = "F4",              Action = "F4"        },
    { Text = "F5",  Action = "F5"  },
    { Text = "F6",  Action = "F6"  },
    { Text = "F7",  Action = "F7"  },
    { Text = "F8",  Action = "F8"  },
    { Text = "F9",  Action = "F9"  },
    { Text = "F10", Action = "F10" },
    { Text = "F11", Action = "F11" },
    { Text = "F12", Action = "F12" }
]
MediaLayerKeys = [
    { Icon = "turtle", Action = "MicMute", Stretch = 1  },
    { Icon = "spider",  Action = "Search", Stretch = 1  },
    { Icon = "hedgehog",  Action = "IllumDown", Stretch = 1  },
    { Icon = "penguin",  Action = "IllumUp", Stretch = 1  },
    { Icon = "brightness_low",  Action = "BrightnessDown" },
    { Icon = "brightness_high", Action = "BrightnessUp"   },
    { Icon = "fast_rewind",     Action = "PreviousSong"   },
    { Icon = "play_pause",      Action = "PlayPause"      },
    { Icon = "fast_forward",    Action = "NextSong"       },
    { Icon = "volume_off",      Action = "Mute"           },
    { Icon = "volume_down",     Action = "VolumeDown"     },
    { Icon = "volume_up",       Action = "VolumeUp"       }
]
