MediaLayerDefault = true
ShowButtonOutlines = true
EnablePixelShift = false
FontTemplate = "dejavu"
AdaptiveBrightness = true
ActiveBrightness = 128
PrimaryLayerKeys = [

    { Icon = "backlight_low",  Action = "IllumDown", Stretch = 1 },
    { Icon = "backlight_high", Action = "IllumUp",  Stretch = 1   },
    { Icon = "brightness_low",  Action = "BrightnessDown",  Stretch = 1 },
    { Icon = "brightness_high", Action = "BrightnessUp",   Stretch = 1  },
    { Icon = "fast_rewind",     Action = "PreviousSong",    Stretch = 3 },
    { Icon = "play_pause",      Action = "PlayPause",       Stretch = 3 },
    { Icon = "fast_forward",    Action = "NextSong",        Stretch = 3 },
    { Icon = "volume_off",      Action = "Mute",            Stretch = 1 },
    { Icon = "volume_down",     Action = "VolumeDown",      Stretch = 1 },
    { Icon = "volume_up",       Action = "VolumeUp",        Stretch = 1 },
    { Icon = "music",           Action = "Media",          Stretch = 1 }
]
MediaLayerKeys = [
    { Icon = "refresh", Action = "F5", Stretch = 1  },
    { Icon = "turtle", Action = "Prog1", Stretch = 1  },
    { Icon = "spider",  Action = "Prog2", Stretch = 1  },
    { Icon = "hedgehog",  Action = "Prog3", Stretch = 1  },
    { Icon = "penguin",  Action = "Prog4", Stretch = 1  },
    { Icon = "telegram",  Action = "Chat", Stretch = 1  },
    { Icon = "wallpaper",  Action = "Images", Stretch = 1  },
    { Icon = "menu",  Action = "KpMinus", Stretch = 1  },
    { Icon = "terminal",  Action = "KpEqual", Stretch = 2  },

    { Icon = "apps",  Action = "AllApplications", Stretch = 1  },
    { Icon = "close",  Action = "Close", Stretch = 1  },
    { Icon = "downloads",  Action = "Documents", Stretch = 1  },
    { Icon = "logout",  Action = "Logoff", Stretch = 1  }
]
