#!/bin/sh
while true; do
  status=$(~/.config/rofi/dbus-spotify status)
  image=$(wget -q --output-document=/tmp/spotify-art.jpg $(dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'|egrep -A 1 "artUrl"|cut -b 44-|cut -d '"' -f 1|egrep -v ^$) 2> /dev/null)]
  if [ "$status" = "Playing" ]; then
    sleep 5
  elif [ "$status" = "Paused" ]; then
    sleep 1
  fi
done
